format = "$username@$hostname $directory$git_branch$git_status$line_break$character"

[character]
success_symbol = "> "
error_symbol = "! "
style = "green"

[directory]
style = "yellow"

[git_branch]
style = "cyan"
symbol = ""

[git_status]
style = "red"
symbol = ""

